#!/bin/bash

echo "🚀 ShardeumQuest Vercel Deployment Guide"
echo "========================================"
echo ""

echo "1. First, you need to push this to GitHub:"
echo "   - Create a new repository on GitHub named 'shardeum-quest'"
echo "   - Run these commands:"
echo "   git remote add origin https://github.com/yourusername/shardeum-quest.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""

echo "2. Then go to vercel.com and:"
echo "   - Sign up/login with GitHub"
echo "   - Click 'New Project'"
echo "   - Import your shardeum-quest repository"
echo "   - Use these settings:"
echo "     Framework: Other"
echo "     Build Command: npm run vercel-build"
echo "     Output Directory: frontend/build"
echo ""

echo "3. Environment Variables (CRITICAL!):"
echo "   Add these in Vercel dashboard:"
echo "   MONGODB_URI=mongodb+srv://Cluster33216:VFBiYkVjYF1E@cluster33216.ldxyoqv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster33216"
echo "   CONTRACT_ADDRESS=0x1169Ea80acD04e4379a72e54Dd4B1810e31efC14"
echo "   REACT_APP_CONTRACT_ADDRESS=0x1169Ea80acD04e4379a72e54Dd4B1810e31efC14"
echo "   PRIVATE_KEY=72c5b7841f0cebdf4d84805e05fc4d3fadd33824d36ae900df1a383bc0c4c41a"
echo "   JWT_SECRET=your-super-secure-jwt-secret-change-this"
echo "   NODE_ENV=production"
echo ""

echo "4. Deploy!"
echo "   - Click Deploy"
echo "   - Wait for build to complete"
echo "   - Your app will be live at https://your-project.vercel.app"
echo ""

echo "✅ Your project is ready for deployment!"
echo "All configuration files have been created:"
echo "- vercel.json (deployment config)"
echo "- backend/api/index.js (serverless functions)"
echo "- Updated package.json files"
echo "- .env.vercel (environment variables template)"
echo ""

echo "📖 For detailed instructions, see VERCEL_DEPLOYMENT.md"